name: arjen
favicon: null
layout_spectrum: 0
typography_spectrum: 0.56395
title: arjen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#01538b'
    - '#feac02'
    - '#456c95'
    - '#fcfcfc'
    - '#a6712f'
  brandStrength: 1
  lightness: 0.9375
  saturation: 1
  rhythmicContrast: 0
purpose: []
