analytics: {}
color:
  brandColors:
    - '#01538b'
    - '#feac02'
    - '#456c95'
    - '#fcfcfc'
    - '#a6712f'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0.446083
  saturation: 0.4375
cta: {}
layout_spectrum: 0.771396
name: arjen
opengraph: {}
purpose: []
typography_spectrum: 0.406531
